# radio.py - contributed by @jarvisteach

import microbit
import time
from queue import Queue
from threading import Thread

fileName = pos = -1
groups = ["brunel", "eiffel", "hawkins", "musk", "stephenson"]
queue = Queue()

def processFile():
    while True:
        with open(fileName, "a") as fileObj:
            while not queue.empty():
                incoming = queue.get()
                print(" >>", incoming)
                fileObj.write(incoming + "\n")
        

def changeGroup():
    global pos, fileName
    pos += 1
    pos %= len(groups)
    microbit.display.show(groups[pos][0])
    fileName = "/tmp/" + groups[pos] + ".csv"
    print("Switched to group: ", groups[pos])

def stripMakeCodeHeader(incoming):
    """strip off byte header generated by makecode"""
    pos = incoming.rfind("\\x")+4
    header = incoming[:pos]  #TODO: unused
    body = incoming[pos:-1]
    return body

changeGroup()

t = Thread(target=processFile)
t.start()

microbit.radio.config(group=132, queue=10)
microbit.radio.on()

while True:
    time.sleep(0.1)
    incoming = microbit.radio.receive_bytes()

    if incoming != "None":  #TODO: api.py will need better None handler.
        incoming = stripMakeCodeHeader(incoming)
        if "," not in incoming:
            incoming = "UNKNOWN, " + incoming
        queue.put(time.strftime('%a %H:%M:%S') + ", " + incoming)
        
    if microbit.button_a.was_pressed():
        changeGroup()
